<?php

/**
 * @file
 * This module provide color value of field added by color_field module.
 */



function color_value_preprocess_commerce_product(&$variables)
{
  $product_variations = $variables['elements']['#commerce_product']->{'variations'}->referencedEntities();

  $colors = array_map(function($item){
    return $item->{'field_background_color'}->{'color'};
  }, $product_variations);

  $variables['background_color'] = join(", ", $colors);
}
